name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        # Use pip version < 24.1 for compatibility with older Kivy versions
        pip install "pip<24.1"
        pip install buildozer cython==0.29.33
        
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev libssl-dev python3-dev python3-pip
        sudo apt install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        
    - name: Install Android SDK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        mkdir -p $ANDROID_HOME
        cd $ANDROID_HOME
        wget https://dl.google.com/android/repository/commandlinetools-linux-6514223_latest.zip
        unzip commandlinetools-linux-6514223_latest.zip
        # Check the actual directory structure after extraction
        echo "Directory structure after unzip:"
        ls -la
        # Create cmdline-tools/latest directory structure
        mkdir -p cmdline-tools/latest
        # Handle different possible directory structures
        if [ -d "cmdline-tools" ] && [ -d "cmdline-tools/bin" ]; then
          # Standard structure with bin directory inside cmdline-tools
          mv cmdline-tools/* cmdline-tools/latest/
        elif [ -d "tools" ] && [ -d "tools/bin" ]; then
          # Direct tools directory
          mv tools cmdline-tools/latest/
        else
          # Other structure - move everything to latest
          mv * cmdline-tools/latest/ 2>/dev/null || true
        fi
        # Ensure we have the right structure
        echo "cmdline-tools directory structure:"
        ls -la cmdline-tools/
        echo "cmdline-tools/latest directory structure:"
        ls -la cmdline-tools/latest/
    
    - name: Accept Android SDK licenses
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        # Ensure sdkmanager exists
        echo "Checking sdkmanager location:"
        ls -la $ANDROID_HOME/cmdline-tools/latest/bin/ || echo "sdkmanager directory not found"
        # Accept licenses using full path to sdkmanager
        mkdir -p $HOME/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/.android/repositories.cfg
        if [ -f "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true
        else
          echo "sdkmanager not found, skipping license acceptance"
        fi
        
    - name: Initialize buildozer
      run: |
        buildozer init
      continue-on-error: true
      
    - name: Build APK
      run: |
        buildozer android debug
      timeout-minutes: 45
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: RehabGPT-APK
        path: bin/*.apk
        if-no-files-found: warn
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          *.log
          .buildozer/**/*.log
        if-no-files-found: ignore
      if: always()