name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev libssl-dev python3-dev python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        sudo apt install -y git zip unzip openjdk-11-jdk
        
    - name: Install buildozer and dependencies
      run: |
        pip install "pip<24.1"
        pip install Cython==0.29.33
        pip install -r requirements.txt
        pip install buildozer
        
    - name: Set up Android environment
      run: |
        # Set environment variables
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/build-tools/latest" >> $GITHUB_ENV
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
        
    - name: Install and configure Android SDK
      run: |
        # Create Android SDK directory
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        
        # Download and extract command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-6514223_latest.zip
        unzip commandlinetools-linux-6514223_latest.zip
        
        # Organize directory structure
        mkdir -p cmdline-tools/latest
        mv cmd*/* cmdline-tools/latest/ 2>/dev/null || true
        rm -rf cmd*
        
        # Verify structure
        ls -la cmdline-tools/latest/
        
    - name: Accept Android SDK licenses
      run: |
        cd $HOME/android-sdk
        
        # Create repositories.cfg file
        mkdir -p $HOME/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/.android/repositories.cfg
        
        # Accept licenses automatically
        yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses || true
        
    - name: Install required Android SDK packages
      run: |
        cd $HOME/android-sdk
        
        # Install platform-tools and build-tools
        cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30" || true
        
        # Verify installation
        ls -la $HOME/android-sdk/
        if [ -d "build-tools" ]; then
          ls -la $HOME/android-sdk/build-tools/
        fi
        
    - name: Initialize buildozer
      run: |
        buildozer init
      continue-on-error: true
      
    - name: Update buildozer.spec
      run: |
        # Update buildozer.spec to use our Android SDK
        echo "android.accept_sdk_license = True" >> buildozer.spec
        echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec
        
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
    
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rehabgpt-apk
        path: bin/*.apk
        if-no-files-found: warn